name: 'Integration test'
description: 'Integration test'
inputs:
  keystore:
    description: 'Base64 encoded Keystore'
    required: true
  keyPassword:
    description: 'Key Password'
    required: true
  keyAlias:
    description: 'Key Alias'
    required: true
  test:
    description: 'Test file'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Decode Keystore
      run: echo "${{ inputs.keystore }}" | base64 --decode > android/app/key.jks
      shell: bash

    - name: Build AndroidTest
      run: ./gradlew app:assembleAndroidTest
      working-directory: android
      shell: bash
      env:
        KEY_PASSWORD: ${{ inputs.keyPassword }}
        KEY_ALIAS: ${{ inputs.keyAlias }}

    - name: Build Debug APK
      run: ./gradlew app:assembleDebug -Ptarget=`pwd`/../integration_test/${{ inputs.test }}.dart
      working-directory: android
      shell: bash
      env:
        KEY_PASSWORD: ${{ inputs.keyPassword }}
        KEY_ALIAS: ${{ inputs.keyAlias }}

    - name: Run tests in Firebase Test Lab
      run: |
        /home/netanel/google-cloud-sdk/bin/gcloud firebase test android run \
          --type instrumentation \
          --app build/app/outputs/apk/debug/app-debug.apk \
          --test build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
          --device model=Pixel3,version=30,locale=en,orientation=portrait \
          --timeout 30m
      shell: bash
